lezgro_mobd:
    resource: "@LezgroMobdBundle/Resources/config/routing.yml"
    prefix:   /mobd

#ApplicationHelloBundle:
#    resource: "@ApplicationHelloBundle/Resources/config/routing.yml"
#    prefix:   /


# app/config/routing.yml
#homepage:
#    pattern:  /
#    defaults: { _controller: LezgroMobdBundle:Default:index }
    

