Entities\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    login:
      type: string
      length: 100
    name:
      type: string
      length: 255
    email:
      type: string
      length: 100
