<?php

namespace Lezgro\MobdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendsRepository extends EntityRepository
{
}
